apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-coll-65f984e537454625a6c09ade35a3effa-depl
  labels:
    app: users-coll-65f984e537454625a6c09ade35a3effa
    release: prometheus  # Added label for PodMonitor discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-coll-65f984e537454625a6c09ade35a3effa
      release: prometheus  # Added label for PodMonitor discovery
  template:
    metadata:
      labels:
        app: users-coll-65f984e537454625a6c09ade35a3effa
        release: prometheus  # Added label for PodMonitor discovery
    spec:
      containers:
        - name: users-coll-65f984e537454625a6c09ade35a3effa
          image: 216084506783.dkr.ecr.ap-south-1.amazonaws.com/backstract_apps:users-coll-65f984e537454625a6c09ade35a3effa
          imagePullPolicy: Always
          ports:
            - containerPort: 7070
              name: http  # Optional for HTTP traffic
            - containerPort: 7070 #same as the deployed code
              name: metrics  # Added port for metrics scraping